### ISSUE TITLE
Update names and logos in demos

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Viz#128]
Names of the demos and logo should be updated:

* The name on the upper-left corner (UDV) must be updated to UD-Viz and become linkable to the UD-Viz github repository 
* LIRIS and IMU logos must be  moved to the left side (next to Sign In)
* Rename the demos from the index.html page (http://rict.liris.cnrs.fr/UDVDemo/UDV/UDV-Core/) :
   * Demos -> Thematic Demos
   * UDV Full modules demo -> All Components demos
   * UDV-stable demo -> UD-SV for cultural heritage - Fab-Pat
* Thematic demos have their thematic name writtent in the center of the upper bar; e.g. "UD-SV for cultural heritage - Fab Pat" at the top of the Fab-Pat demo
* On the right side of the upper bar: Add a "Data Partners" "category" and add the logo of the Grand Lyon and of Auvergne Rhone Alpes

When these modifications are done, send the link of the demo to patrimoine Aura.

**Comment by jailln** [comment]
What must be done for Thursday:

* Update the "Fab-Pat demo" wih the Aura logo
* Verify that the images are placed correctly (remove the others) 
* Updates the rights holders following this convention: Author: B. Decrock ; Copyright: © Région Rhône-Alpes, Inventaire général du patrimoine culturel © Ville de Lyon

**Comment by jailln** [comment]
Send the demo link to Aura when it's done.

**Comment by EricBoix** [comment]
UD-Viz is now a package as opposed to end-user applications. As such Ud-Viz is neutral and should not
bear any project partner name, contributors, sponsors...
Such IP concerns, branding, legalize, ownership should be handled in end-user applications.
Refer to specific project demos e.g. [Imuv/flyingCampus](https://demo.liris.cnrs.fr/vcity/flyingcampus/).
Closing.
