### ISSUE TITLE
Update and align terrain imagery and elevation source

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Viz#135]
In our demo, we currently use:

* [The 2009 terrain imagery](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/BaseDemo/js/BaseDemo.js#L352)
* [The 2012 terrain elevation](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/BaseDemo/js/BaseDemo.js#L371)

Update these sources to the 2015 versions:

* [The 2015 terrain imagery](https://data.grandlyon.com/jeux-de-donnees/orthophotographie-2015-metropole-lyon-format-ecw/donnees)
* [The 2015 terrain elevation](https://data.grandlyon.com/jeux-de-donnees/image-relief-2015-metropole-lyon/donnees)

This may boil down to just changing the links in UD-Viz.

**Comment by clementcolin** [comment]
Before updating the links in UD-Viz, we need to ask data.grandlyon to fix the 2015 terrain imagery, which is empty at this moment

**Comment by ggesquiere** [comment]
I thought that it was already done ? If it is not, you may ask to the Grand Lyon Data service

**Comment by clementcolin** [comment]
I just asked the Grand Lyon Data service to fix the data.

For information, if you look at the [2012](https://data.grandlyon.com/jeux-de-donnees/orthophotographie-2012-metropole-lyon/donnees) orthophoto, you can see the image. 
But the [2015](https://data.grandlyon.com/jeux-de-donnees/orthophotographie-2015-metropole-lyon-format-ecw/donnees) and [2018](https://data.grandlyon.com/jeux-de-donnees/orthophotographie-2018-metropole-lyon-format-ecw/donnees) images are empty

**Comment by jailln** [comment]
I didn't know that the 2018 vintage was already available, let's go for this one then! 
@clementcolin please let me know when they have updated it.

**Comment by ggesquiere** [comment]
I have the same comments. Go to 2018. We may have some mismatch with CityGML 2015 ?

**Comment by jailln** [comment]
> I have the same comments. Go to 2018. We may have some mismatch with CityGML 2015 ?

Let's hope not! It shouldn't be the case since we already don't use the same terrain and elevation vintages as the CityGML vintage and it works. Also, the terrain doesn't change much in the real world between two vintages.

**Comment by clementcolin** [comment]
I had an answer this morning, according to Grand Lyon Data service, this layer WMS is hidden and is not listed for the moment. The correct layer to specify is the following : "Ortho2018_Dalle_unique_8cm_CC46". I'll change it and do a PR.

As for the elevation layer, I agree with jailln, it must have not changed that much.

**Comment by jailln** [comment]
Cool thanks! Still, could you also update the elevation layer please ?

**Comment by clementcolin** [comment]
Done in PR #136
