### ISSUE TITLE
Automatically handle properties linked to tilesets

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#138]
When using [properties](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/3DTiles/Model/CityObject.js#L67) from the batch table, all mechanisms linked to those properties, such as [display them](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Modules/CityObjects/View/AttributeFilterSelector.js#L37) or [link a document to an object by a property](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Modules/Links/ViewModel/LinkProvider.js#L277) , are made only using one given property, which is "cityobject.database_id".
Maybe we can set a rule that everytime we create a tileset, instead of using "cityobject.database_id" or "ifc.if", we must use a generic term "id" as an attribute.
Also, we may need to add the possibility to display all attributes linked to an object, somewhere near [here](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Modules/CityObjects/View/AttributeFilterSelector.js#L37)

**Comment by valentinMachado** [comment]
related https://github.com/VCityTeam/py3dtilers/issues/117
