### ISSUE TITLE
Config File should not be a global one

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#140]
## How things are
The information required for the definition demo is currently scattered
   - for the "code" part:  a [demo specific directory](https://github.com/VCityTeam/UD-Viz/tree/master/UD-Viz-Core/examples)
   - for the "data" part: [generalDemoConfig.json](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/examples/data/config/generalDemoConfig.json). Notice that currently `generalDemoConfig.json` gathers the information required for many demonstrations, making this file too big, ill-structured, almost unreadable and bloated.

Besides many (most of them) demos are too specific to belong within the UD-Viz repository.
In fact they belong within [UD-Reproducibility/Demos](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Demos)
where they should be relocated. 

Hence creating a new demonstration becomes a weird (undocumented) process that 
is hard to infer out of such a confusing situation.

## How things should be
For the sake of modularity, each demo
  - should be entirely defined within directory in  [UD-Reproducibility/Demos](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Demos) (and no information should "contaminate" the UD-Viz repository)
  - should have a [Demo.html](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/examples/DemoLimonest/Demo.html) and a [Demo.js](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/examples/DemoLimonest/Demo.js) files (defining the code i.e. the modules is assembles)
  - should have its own configuration file (the part of [generalDemoConfig.json)](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/examples/data/config/generalDemoConfig.json) concerning that demo), its CSS, the logos it wishes to use, the layers and data extents... 

## What needs to be changed
 1. Modify/extend the [BaseDemo.js](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/BaseDemo/js/BaseDemo.js) class so that
     * the logos used by the [html() getter](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/BaseDemo/js/BaseDemo.js#L55) can be easily configured by a specific demo (this "html() getter" 
       could call another getter on a logs attribute whose setter whould be called by a demo ?)
     * ease the (demo) usage of its [configuration](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/BaseDemo/js/BaseDemo.js#L38) : logo-imu and logo-liris should not be hardwired
     
 2.  Move the [example/Demos](https://github.com/VCityTeam/UD-Viz/tree/master/UD-Viz-Core/examples) to [UD-Reproducibility/Demos](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Demos) 
 
 3. Disseminate [generalDemoConfig.json](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/examples/data/config/generalDemoConfig.json) to those demos

**Comment by EricBoix** [comment]
PR #156 changes the first point of what need to be changed.

**Comment by EricBoix** [comment]
Separation realized between UD-Viz and UD-Viz-demo.
Closing.
