### ISSUE TITLE
Zoom on a specific tileset

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#146]
Related issue: #397

## The need
In order to help with the debugging process of computed 3dTiles tilesets, but also to help the user visualize the data, there is a need to add to the `LayerManager` the possibilty to focus / zoom on a specific tileset (e.g. the one selected in a the `LayerManager`, even if this tileset is not loaded.

**Comment by EricBoix** [comment]
I'm confused. How can one focus/zoom on an element when its geometry (geography)
is yet unknown since the data was not loaded (the tileset is not loaded) !?

**Comment by clementcolin** [comment]
The geometry may be unknown but we still every information we need to load a tileset (in the tileset.json) : the bounding box (or the extent) of each tile. With this information, we load the geometry only when needed, i.e when the bounding box is visible from the camera.
This feature could be useful for debug purpose, such as check if a tileset is correctly loaded but in a wrong place, but also for practice purpose, such as focus on a specific tileset that is far from our camera location (if we are in Lyon and we want to go to Paris).

**Comment by EricBoix** [comment]
Oh, I see: the [main tileset JSON file](https://github.com/CesiumGS/3d-tiles/tree/master/specification#tileset-json) was loaded but the [pointed tiles](https://github.com/CesiumGS/3d-tiles/tree/master/specification#tiles) are NOT yet loaded...

Hence you can provide some helpful camera focus based on the bounding boxes provided within the main tileset JSON file.
Got it !

**Comment by valentinMachado** [comment]
Is [this function](https://github.com/VCityTeam/UD-Viz/blob/dade952b37b7b2e84cf554a5b747325a1b18c0cd/packages/browser/src/Component/ItownsUtil.js#L394) doing what you need ? Btw I don't get how there is layer has an attribute extent since I can't figure it out where it's initialized

**Comment by clementcolin** [comment]
Yes, closing this issue
