### ISSUE TITLE
[ConsultDoc Demo] Use "classic" import mecanism for jQuery 

### ISSUE THREAD

**Issue by sophiaab** [VCityTeam/UD-Viz#15]
In UDV-Core/examples/Demo.html
````
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
````

The dependency on Jquery is already expressed (with this PR) in package.json.
The import of Jquery thus doesn't need to depend on on an external server (ajax.googleapis.com) to be active.
Use the "classic" import mechanism to remove that URL (and the dependency towards an active external server as well as the need for IP connectivity).

**Comment by EricBoix** [comment]
Jquery is now [properly imported](https://github.com/VCityTeam/UD-Viz/blob/master/package.json#L29) thanks to @valentinMachado
