### ISSUE TITLE
[Temporal Module] Assert the graph window still works and maybe rework it

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Viz#154]
* Assert that the graph window works
* Rework some of its design, e.g. assert [this "asynchronous" method](https://github.com/VCityTeam/UD-Viz/pull/151/files#diff-4b46cf988afb5a4bbdf7c64ba1c52f26767eaa3ba5cf0b0335290d0ffee027abR29) is useful and [avoid piggyback](https://github.com/VCityTeam/UD-Viz/pull/151/files#diff-4b46cf988afb5a4bbdf7c64ba1c52f26767eaa3ba5cf0b0335290d0ffee027abR42)

**Comment by valentinMachado** [comment]
If this still relevant ?

**Comment by jailln** [comment]
I don't remember what the graph window was ^^

**Comment by valentinMachado** [comment]
that's answered my question ^^
