### ISSUE TITLE
Clean up eslint errors

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#158]
eslint errors have accumulated and should be cleaned up. Once this is complete, we can reinstate the practice of running lint before committing new code.
The ability to run eslint with `npm run lint` was removed during UD-Viz refactoring.

Refer to [this PR](https://github.com/VCityTeam/UD-Reproducibility/pull/24) for a small footprint manner of
re-introducing this feature.

For trendy IDE indicate how to enforce the same linting rules.
For example, vscode's [eslint plugin allows to use](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6) the same [.eslintrc.js](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/.eslintrc.js) configuration file that `npm run lint` is configured to use.
This is to avoid going back and forth between the various IDE eslint settings...

**Comment by EricBoix** [comment]
Fixed by PR #178
