### ISSUE TITLE
The LayerChoice module demo is not linked from the general menu

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#160]
The default index.html that lists [all the Modules examples](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/index.html#L88) misses the [LayerChoice](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Modules/LayerChoice/examples/Demo.html) entry.

**Comment by DiegoVinasco** [comment]
closed during ud-viz sprint
