### ISSUE TITLE
Smooth camera travel doesn't work anymore

### ISSUE THREAD

**Issue by sophiaab** [VCityTeam/UD-Viz#17]
In "ConsultDoc" module (in the PR #12, this issue was about the "Documents" module), the camera travel doesn't work. The camera moves directly from one point to another, the movement is not smooth anymore.

**Comment by jailln** [comment]
This is most probably due to the version of iTowns we use; upgrading to the last version should resolve this problem.

**Comment by jailln** [comment]
Done.
