### ISSUE TITLE
Zoom on a specific 3DTiles Layer

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#176]
In order to visualize a 3DTiles layer that is not currently visible (i.e not in the field of view), there is a need to be able to move camera on it using the extent of the 3DTiles layer.
 
This functionality would help to debug 3dtiles.

**Comment by clementcolin** [comment]
Before solving this issue, there is a need to fix the extent and bounding box of incoming 3DTiles, created with py3dtiles.

**Comment by clementcolin** [comment]
Wrong bounding box calculation was fixed in [this PR](https://github.com/VCityTeam/py3dtiles/pull/13), this issue can now be fixed

**Comment by EricBoix** [comment]
Duplicate of [issue 146](https://github.com/VCityTeam/UD-Viz/issues/146).
Closing.
