### ISSUE TITLE
Reconcile prettier and eslint

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#181]
Refer to [this comparison](https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint)

**Comment by mathieuLivebardon** [comment]
- We should use this package https://github.com/prettier/prettier-eslint with a .prettierrc and .eslintrc 
- We need more rules than those that already exist in .eslintrc, but also for prettier because eslint only looks at Javascript

**Comment by DiegoVinasco** [comment]
this is fixed in IMUV
