### ISSUE TITLE
Select and highlight a cityObject from uri

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#185]
There is a need of a feature that allows to select an object from the URI or at least by layer id and object id, highlight it so that we can see it through other object and zoom on it.

There is already a  [method in LinkProvider.js](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/Links/ViewModel/LinkProvider.js#L376)  or in the [3DTiles debug extension](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/Extensions/3DTilesDebug/views/3DTilesDebugWindow.js#L152) that highlight a selected object from tile id and batch id. 

Following this method, there is a need to add the possibility to specify also the layer.

What is needed : 
- [x] a method to select a cityObject from is ID and layerID in LayerChoice for example
- [x] the highlighted object must be seen through other objects. It is a render issue, maybe implying shader programming
- [x] zoom on the selected object (may be linked to [this issue](https://github.com/VCityTeam/UD-Viz/issues/176)) 
- [x] Allow to pass parameter from URI to call UD-Viz on a specific object (may need its own issue and reflexion about an UD-Viz API)
- [x] Pull SPARQL Module code from [UD-Demo-GeoDataDays](https://github.com/VCityTeam/UD-Demo-GeoDataDays-MultiNavigation-Chaufferie)
- [x] Document code

**Comment by DiegoVinasco** [comment]
this was partially done for 3DTiles with `gml:id`s as IDs for their features and needs to be continued in #426

**Comment by DiegoVinasco** [comment]
This can be closed by pulling the new SPARQL module code from the [geodatadays demo](https://github.com/VCityTeam/UD-Demo-GeoDataDays-MultiNavigation-Chaufferie) into UD-Viz
