### ISSUE TITLE
Extract all documents demonstration associated code to its own application 

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#195]
As the document part of UD-Viz needs a media server to be working, all associated code should be part of an external application that UD-Viz would be able to import.

Also, this would mean to delete the associated example and to create a demonstration on its own

**Comment by valentinMachado** [comment]
Back end of widget (@ud-viz/browser) could be implement in @ud-viz/node and share code with widget code in @ud-viz/core
