### ISSUE TITLE
Zoom in/out handler

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#199]
I am not sure if this is the right place to post this issue (please direct me to the right repo if needed)

Right now when a user zoom out to much the scene brutally disappears

For instance here:
http://rict.liris.cnrs.fr/UDVDemo/UDV/UDV-Core/examples/DemoFull/Demo.html

We should have a better way to handle the zNear and zFar depending on the Camera Position so that the scene is always displayed even if it is a tiny scene

<img width="1286" alt="Screenshot 2021-07-22 at 14 57 38" src="https://user-images.githubusercontent.com/3928502/126642642-4a685086-5999-44fd-9aba-bfd46592abae.png">

**Comment by valentinMachado** [comment]
resolve by this pr https://github.com/VCityTeam/UD-Viz/pull/228

**Comment by agrignard** [comment]
I am reopening this issue as it looks like I still have the same problem.

I am not sure if we understood ell each other, hat I was referring in this issue is the fact when you zoom out of the inital camera position you very quickly go in a totally blue screen mode where you don't see your scene anymore.

You mentionit was resolved here https://github.com/VCityTeam/UD-Viz/pull/228 but I am not sure I see a big difference (I am currently using UD_VIZ 2.36). Is it because the extent is too small?

![Untitled mov](https://user-images.githubusercontent.com/3928502/163170462-7ffd5465-c41b-40bb-a278-e41ca48d7f3c.gif)

**Comment by valentinMachado** [comment]
The fix I have done was for [View3D](https://github.com/VCityTeam/UD-Viz/blob/master/src/Views/View3D/View3D.js) which is still not use in the AllWidget example

https://github.com/VCityTeam/UD-Viz/issues/234

**Comment by agrignard** [comment]
Seems to be fixed in this branche
https://github.com/VCityTeam/UD-Viz/compare/master...dynamic-near-far
