### ISSUE TITLE
Some comment/question about UD-Viz Tutorial

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#201]
I just write here some stuff whil following the tutorial (placing my self has a pure beginner)
- [x] Some part are in French here
https://github.com/VCityTeam/UD-Viz/blob/dev-unstable/Doc/Devel/LocalGameTutorial.md#working-environment

- [x] "Et enfin hebergez le dossier UD-Viz", would it be possible to be more explicit about what is means to "hebergez le dossier?" 
- [x] "For this tutorial you will need to import ud-viz in your project" how do you do this? 
- [x] To keep this tutorial simple ud-viz is imported this way, but a npm package exists and it's recommended to use it since you can benefit of the update with it. => yes I would prefer to do that than downloading in local my udv.js how do I do this? 
- [x] Arriving at this stage https://github.com/VCityTeam/UD-Viz/blob/dev-unstable/Doc/Devel/LocalGameTutorial.md#create-a-your-game I am not able to see anything in my browser (using Chrome).
<img width="830" alt="Screenshot 2021-07-26 at 15 53 16" src="https://user-images.githubusercontent.com/3928502/127000456-fd2030af-3b84-41ba-931b-b97147ea26c9.png">
<img width="830" alt="Screenshot 2021-07-26 at 15 53 28" src="https://user-images.githubusercontent.com/3928502/127000466-1a9335c0-90fb-4f18-a7a4-7202f8756a84.png">

**Comment by mathieuLivebardon** [comment]
- The tutorial has been rewritten following this review, in order to clarify some steps. (Available only on the [dev-unstable](https://github.com/VCityTeam/UD-Viz/blob/dev-unstable/Doc/Devel/LocalGameTutorial.md) branch for the moment.)
- For the part of importing ud-viz with npm another documentation document will be produced in the future, for the moment we are inspired by the documentation of [THREE.JS](https://threejs.org/docs/#manual/en/introduction/Creating-a-scene) which to begin with uses a bundle for importing.

**Comment by agrignard** [comment]
Ok so the first 4 point are now ok.

Using the dev-unstable branch I am still stuck at this stage: https://github.com/VCityTeam/UD-Viz/blob/dev-unstable/Doc/Devel/LocalGameTutorial.md#parameterize-itowns-layers

I can see the blue world 
<img width="1014" alt="Screenshot 2021-09-15 at 18 09 45" src="https://user-images.githubusercontent.com/3928502/133469727-57c9529d-b463-4a08-87cb-5893c55c47fa.png">



but ones I copy/paste this lines to see the texture of Lyon I don't see anything 



`````
"background_image_layer": {
    "url": "https://download.data.grandlyon.com/wms/grandlyon",
    "name": "Ortho2018_Dalle_unique_8cm_CC46",
    "version": "1.3.0",
    "format": "image/jpeg",
    "layer_name": "Base_Map",
    "transparent": true
},
"elevation_layer": {
    "url": "https://download.data.grandlyon.com/wms/grandlyon",
    "name": "MNT2018_Altitude_2m",
    "format": "image/jpeg",
    "layer_name": "wms_elevation_test"
}
`````

**Comment by mathieuLivebardon** [comment]
Are there any errors in the browser console?

**Comment by agrignard** [comment]
This is what I have  
<img width="1787" alt="Screenshot 2021-09-16 at 11 56 23" src="https://user-images.githubusercontent.com/3928502/133592068-18bccaf3-a488-46f7-bbb3-6662ba00ae98.png">

**Comment by agrignard** [comment]
Ok so the exact syntax is , which was not very clear on the tutorial. I let youd ecide how to update it in the unstable branch and I think we are ok to close this issue after. What was not clear for me is that I was litterally pasting the code right after what was already there (as written in the tuto)

Thanks!

`````
{
  "game": {
    "fps": 30,
    "shadowMapSize": 2046,
    "skyColor": {
      "r": 0.4,
      "g": 0.6,
      "b": 0.8
    }
  },
  "itowns": {
    "radiusExtent": 1000
  },
  "background_image_layer": {
    "url": "https://download.data.grandlyon.com/wms/grandlyon",
    "name": "Ortho2018_Dalle_unique_8cm_CC46",
    "version": "1.3.0",
    "format": "image/jpeg",
    "layer_name": "Base_Map",
    "transparent": true
},
"elevation_layer": {
    "url": "https://download.data.grandlyon.com/wms/grandlyon",
    "name": "MNT2018_Altitude_2m",
    "format": "image/jpeg",
    "layer_name": "wms_elevation_test"
}
}
`````

**Comment by agrignard** [comment]
Ok so same just after where do we place those line this is not clear.

`````
"3DTilesLayer": {
    "id": "3d-tiles-layer-building",
    "url": "./assets/lod_flying_campus/tileset.json",
    "color": "0xFFFFFF",
    "initTilesManager": "true"
}
``````

The more I use the tutorial the more I think you should provide some waypoint step where you provide the actual working ```local_game_config.json```

**Comment by mathieuLivebardon** [comment]
I added a link to the final version of each file, this will allow the user to compare at each step his version and the final one.
I think I can close this issue.
