### ISSUE TITLE
Multilayer example bug

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#222]
Buildings are not landing on the ground in this [example](https://github.com/VCityTeam/UD-Viz/tree/master/examples/MultiLayer)
![bug_multilayer](https://user-images.githubusercontent.com/14295096/133062734-1a1cc6b4-8e3f-4b77-b3f8-6094015f97e8.png)

**Comment by clementcolin** [comment]
Fixed in this [pr](https://github.com/VCityTeam/UD-Viz/pull/237)
