### ISSUE TITLE
Integrate temporal dimension related modifications of iTowns cleanly and document the process to add new fonctionnalities to iTowns

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Viz#23]
## The problem

Currently, when we need to modify iTowns, we create a fork and work on a branch. Then, we configure UDV to import this branch instead of iTown's master branch. 

This is bad because new features are on branches of personal repositories and we need to rebase these branches continually. Moreover, when there will be more than one functionnality added to iTowns this way, the framework will start being heavy.

Note that the right way would be to make a PR to iTowns. This is not possible in some cases (e.g. temporal dimension handling for 3D Tiles) because it is not a standard functionnality (yet :) ) and thus iTowns won't accept it.

In this particular case, it seems that it is possible to extend iTowns with new functionnalities directly from the component using it (UDV in our case) ([see this issue](https://github.com/iTowns/itowns/issues/529)); especially by creating Providers and Processing directly from the component using it.

## Actions

 * [ ] Try to implement the temporal dimension handling by extending iTowns within UDV
 * [ ] Document the process

**Comment by jailln** [comment]
Ongoing....

**Comment by jailln** [comment]
I think this issue can be closed since you now contribute to itowns and use these contributions in ud-viz? 
Regarding the proj4 and three dependencies, the itowns js bundle currently embeds the peer dependencies (threejs and proj4) which is indeed an issue when working with this bundle in a project that also uses these libraries. I actually faced the same issue and there is a [discussion](https://github.com/iTowns/itowns/discussions/1802) about it. I started working on it on [the following branch](https://github.com/jailln/itowns/tree/bundle-without-peer-dep). You can use it until it gets merged in itowns main repo: rebase this branch on the branch you want to build and run `npm run build`, it will build an itowns bundle without proj4 and threejs (which you must import in your project).

**Comment by valentinMachado** [comment]
> I think this issue can be closed since you now contribute to itowns and use these contributions in ud-viz? 

Right I was not sure to understand the original issue. I am closing this

>Regarding the proj4 and three dependencies, the itowns js bundle currently embeds the peer dependencies (threejs and proj4) which is indeed an issue when working with this bundle in a project that also uses these libraries. I actually faced the same issue and there is a [discussion](https://github.com/iTowns/itowns/discussions/1802) about it. I started working on it on [the following branch](https://github.com/jailln/itowns/tree/bundle-without-peer-dep). You can use it until it gets merged in itowns main repo: rebase this branch on the branch you want to build and run `npm run build`, it will build an itowns bundle without proj4 and threejs (which you must import in your project).

The thing here is that I want to use itowns as a npm package (and not a bundle) since in ud-viz we are creating one single bundle that emebed itowns + three + proj4 (maybe the trick would be to point in ud-viz package proj4 and three dependency to the itowns local repo ?). Looks like there is also [a discussion about it](https://github.com/iTowns/itowns/discussions/1919#discussioncomment-3868171).
