### ISSUE TITLE
Align axes of glb imported files and Three

### ISSUE THREAD

**Issue by webanck** [VCityTeam/UD-Viz#257]
I created a simple gizmo in Blender to debug XYZ axes, exported it in glb format and imported it in UD-Viz as an asset (`GameObject`).
The gizmo is composed of a white cube at the origin, and RGB cubes translated along the respective XYZ axes.
The blender file and the two glb export options (with/without `Yup` checked) are provided in this archive: [xyz_rgb_gizmo.zip](https://github.com/VCityTeam/UD-Viz/files/7571500/xyz_rgb_gizmo.zip).

I added a corresponding gizmo compsoed of RGB spheres directly in the Three scene with the following code :
```js
//referential debug gizmo
const sphere = new Shared.THREE.SphereGeometry(1, 32, 16);
const red = new Shared.THREE.MeshBasicMaterial({color: 0xff0000});
const green = new Shared.THREE.MeshBasicMaterial({color: 0x00ff00});
const blue = new Shared.THREE.MeshBasicMaterial({color: 0x0000ff});

const redSphere = new Shared.THREE.Mesh(sphere, red);
const greenSphere = new Shared.THREE.Mesh(sphere, green);
const blueSphere = new Shared.THREE.Mesh(sphere, blue);

redSphere.position.setX(5.);
greenSphere.position.setY(5.);
blueSphere.position.setZ(5.);

redSphere.position.add(worldOrigin);
greenSphere.position.add(worldOrigin);
blueSphere.position.add(worldOrigin);

scene.add(redSphere);
scene.add(greenSphere);
scene.add(blueSphere);
```

The XY axes seems to be wrongly reversed after import (in the default/standard Blender export mode with `Yup` checked) :
![glbGameObject-Three-axes_wrong](https://user-images.githubusercontent.com/6747237/142654932-998aadb9-c8a4-4007-a94c-87c8335f995b.png)

Reversing the XY axes with a (-1, -1, 1) scale factor fixes the problem :
![glbGameObject-Three-axes_aligned](https://user-images.githubusercontent.com/6747237/142654928-82894bc7-a00d-4c94-8044-0fe04c305d1b.png)

**Comment by valentinMachado** [comment]
Could you provide me the gizmo blender .glb that you are using ?

**Comment by webanck** [comment]
@valentinMachado 
Yes, in fact I provided it already (see my initial message):
> The blender file and the two glb export options (with/without Yup checked) are provided in this archive: xyz_rgb_gizmo.zip.

And the gizmo used is the default one:

> The XY axes seems to be wrongly reversed after import (in the default/standard Blender export mode with Yup checked) :

**Comment by valentinMachado** [comment]
I didn't notice it, my bad..

**Comment by valentinMachado** [comment]
I remove the transform at the import then model should be export from blender with Yup unchecked
PR https://github.com/VCityTeam/UD-Viz/pull/337
