### ISSUE TITLE
3DTiles data are stored in the repo

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#259]
Currently, some 3DTiles data are stored in [examples/assets/3DTiles](https://github.com/VCityTeam/UD-Viz/tree/master/examples/assets/3DTiles). Should we not store them elsewhere ? Or is it ok to keep 3DTiles in UD-Viz ?

Highly related issue: #231

**Comment by DiegoVinasco** [comment]
resolved in #388
