### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#261]
Generate the html doc of ud-viz with jsdoc https://jsdoc.app/
See also [this ud-sv issue](https://github.com/VCityTeam/UD-SV/issues/56) (and possibly merge them?).

**Comment by EricBoix** [comment]
Done in [version 2.36.1](https://github.com/VCityTeam/UD-Viz/tree/2.36.2/docs) (or sometimes before it).
