### ISSUE TITLE
Remove examples that are demos

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#265]
The [Multilayer example](https://ud-viz.vcityliris.data.alpha.grandlyon.com/examples/MultiLayer/example.html) does NOT illustrate some UD-Viz feature, but instead illustrates the content of some multi-modal (originating in CityGML data) 3dTiles tileset.

As such this example is in fact a [demo](https://github.com/VCityTeam/UD-SV/blob/master/Vocabulary/Readme.md#Demo) and should be into a separated repository with the [other demos](https://github.com/VCityTeam/UD-SV/blob/master/OnlineDemos.md). 

Related issue: #259

**Comment by LorenzoMarnat** [comment]
Fixed in [this PR](https://github.com/VCityTeam/UD-Viz/issues/343). The multilayer example has been deleted from UD-Viz and the demo redeployed
