### ISSUE TITLE
Unecessary assest

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#270]
Is the [3DTiles/roads/roads.7z](https://github.com/VCityTeam/UD-Viz/blob/master/examples/assets/3DTiles/roads/roads.7z) really required for the `tileset.json` to be correct ? If not remove that file from the repository.

**Comment by EricBoix** [comment]
@LorenzoMarnat May we have your input on this issue please ?

**Comment by LorenzoMarnat** [comment]
No, this file is completely useless
