### ISSUE TITLE
Assert DRYness between avatar example and demo-bon

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#284]
[Diffing](https://stackoverflow.com/questions/1968512/getting-the-difference-between-two-repositories) (vscode does a nicer job than Meld on this) the two files
 - [UD-Viz/.../LocalAvatar.html](https://github.com/VCityTeam/UD-Viz/blob/master/examples/LocalAvatar.html)
 - [Demo-Bron/.../bootstrap.js](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron/blob/master/src/bootstrap.js)
 
 shows that the is a _lot_ of redundancy between those two files. Is this repetition necessary ? Is the code of `bootstrap.js` a uncleaned residue of the contribution of this example to UD-Viz ? When not, is there a technical mean to avoid this redundancy ?

**Comment by webanck** [comment]
Both versions are different; they diverged some time ago and were not meant to be factorized. The `LocalAvatar.html` shows one example of custom shading with post-processing while the `bootstrap.js` file was built up on it, adding parts specific to the demo.

**Comment by EricBoix** [comment]
Thanks @webanck . We will thus keep both versions as they are.
One further question : can we get rid of the lengthy sections of commented out code (both with `//` of `/* ...*/) ?
Or should we keep them on debugging purposes or as illustrative possibilities for the shaders ?
