### ISSUE TITLE
Merge the features developed for the Gratte-Ciel demo

### ISSUE THREAD

**Issue by LorenzoMarnat** [VCityTeam/UD-Viz#293]
New features were developed in the [Gratte-Ciel demo](https://github.com/VCityTeam/UD-Demo-Anthropocene-GratteCiel-). Those [features should](https://github.com/VCityTeam/UD-Demo-Anthropocene-GratteCiel-/issues/8) be implemented in UD-Viz:

- [x] Slideshow
- [ ] Camera settings
- [x] Document those new features (?)

**Comment by agrignard** [comment]
For the record see issue https://github.com/VCityTeam/UD-Demo-Anthropocene-GratteCiel-/issues/8 and https://github.com/VCityTeam/UD-Demo-Anthropocene-GratteCiel-/issues/1

**Comment by DiegoVinasco** [comment]
closing, camera settings do not need to be merged as they are demo specific
