### ISSUE TITLE
Opacity not working on 3DTiles layer

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#298]
## The problem
Within the layer choice widget and when trying to change the opacity of a 3DTiles then
- the layer does have its property `Opacity` changed, 
- yet the 3D display of that layer remains unchanged.

## Notes/hints
- Changing the opacity of other types of layers works fine.
- They are some hints indicating that the problem could be related/linked with styles management.

**Comment by valentinMachado** [comment]
fixed by this [PR](https://github.com/VCityTeam/UD-Viz/pull/612)
