### ISSUE TITLE
Introduce thematics to the examples mosaic

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#309]
## The problem
The examples landing page [index.html](https://github.com/VCityTeam/UD-Viz/index.html) mosaic of demos does not distinguish between widget oriented demos, game oriented demos and 3DTiles oriented demos. Adopt a structured layout that does this editorial choice.

## Notes: 
 * the [deckgl examples page](https://deck.gl/examples) nicely proposes the juxtaposition of a structured side-bar and a structured mosaic
 * [threejs examples page](https://threejs.org/examples/) structures it examples (within the sidebar) with hierarchized categories underlying each demo with a textual description (less clear that deckgl ?)
 * BTW are they other [components](https://github.com/VCityTeam/UD-Viz/tree/master/src/Components) that could be illustrated with demos and that would thus require their own regrouped entry ?

**Comment by CorentinGaut** [comment]
Actually the deployed [mosaic](https://ud-viz.vcityliris.data.alpha.grandlyon.com/) makes the difference between UD-Game and UD-Viz widgets, is this enough or do we need more clarity ?
