### ISSUE TITLE
CityObjects does not refresh displayed attributes on second selection   

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#325]
There appears to be different bugs

## How to reproduce the first bug -- _FIXED_
1. Launch UD-Viz examples (e.g. `npm run build` and `python3 -m http.server` and web-browse on the provided URL...)
2. Select the AllWdigets example of the mosaic
3. Toggle the `CityObjects` widget on
4. Select a first building in the scene: the selected building gets properly highlighted in the scene and the attributes of that building get properly displayed in the CityObject sub-window (ok)
5. Hit the `clear-selection` button: the previously selected building gets properly UN-highlighted (ok) BUT the attributes of that previously selected building remain displayed in he CityObject sub-window (bug)

## How to reproduce the second bug -- _FIXED_

1. Launch UD-Viz examples (e.g. `npm run build` and `python3 -m http.server` and web-browse on the provided URL...)
2. Select the AllWdigets example of the mosaic
3. Toggle the `CityObjects` widget on
4. Select a first building in the scene: the selected building gets properly highlighted and attributes of that building get properly displayed (ok)
5. Select a second building in the scene:  the newly selected building gets properly highlighted BUT its attributes are not displayed (the previously displayed attributes of the first building keep being displayed).

Notice that, if prior to step 4 you first hit the `clear-selection` button (and although the attributes remain erroneously displayed, refer to first above bug) THEN when realizing step 5 (second selection) the attributes of the newly selected building get properly refreshed.

## How to reproduce the third bug -- _FIXED_

1. Launch UD-Viz examples (e.g. `npm run build` and `python3 -m http.server` and web-browse on the provided URL...)
2. Select the AllWdigets example of the mosaic
3. Toggle the `CityObjects` widget on
4. Drag the created sub-window upwards : the sub-window bottom line never appears, that is the sub-window is vertical length is not properly set (bug)

Note if you open the filter second sub-window (hit the `select` button of the Filter section of the first sub-window) and
drag that `City Objects - Filters` sub-window upwards then the same defect appears (that second sub-window is vertical length is not properly set)

## How to reproduce the fourth bug

1. Launch UD-Viz examples (e.g. `npm run build` and `python3 -m http.server` and web-browse on the provided URL...)
2. Select the AllWdigets example of the mosaic
3. Toggle the `CityObjects` widget on : a `City Object` sub-window appears (ok)
4. Within that `City Object` sub-window, hit the `select` button of the Filter section: this will open a second `City Objects - Filters` (ok)
5. Within that second `City Objects - Filters` sub-window pull down the `no-filter` menu and select attributes: the interface changes by adding 3 new entries (ok)
6. Provide e.g. 6 as `tiled Id` and `309` as `batch id` and hit the `set filter` button at the button of that second `City Objects - Filters` sub-window:
    - A filter appears in the first  `City Objects` sub-window (ok)
    -  BUT the filtered `city object` building is not selected in the scene (bug)

Note that is you now select a new building in the scene, then the previously defined filter vanishes (bug in bug ???)

## Document the usage of that widget

The general usage of the filter mechanism is not intuitive (maybe because of the bugs?).
Provide some browsable documentation that is accessible through the widget sub-window (refer to `3DTiles Debug` widget sub-window for an example of such documentation reference).

**Comment by clementcolin** [comment]
FYI, I fixed the two fisrt bugs in this [branch](https://github.com/VCityTeam/UD-Viz/tree/fix_style/src), i'll do a clean PR once the other two are fixed
