### ISSUE TITLE
3DTiles debug widget `Log Tiles Manager` button (apparently) does nothing

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#327]
## How to reproduce the bug

1. Launch UD-Viz examples (e.g. `npm run build` and `python3 -m http.server` and web-browse on the provided URL...)
2. Select the AllWdigets example of the mosaic
3. Toggle the `3DTiles Debug` widget on: a sub-window gets displayed (ok)
4. Hit the `Log Tiles Manager` button at the top of that sub-window (apparently) does nothing (bug)

In fact the `Log Tiles Manager` button properly displays the tileset data structure ... but in the (developer tools) console.

## Possible fixes

Because the returned/displayed data structure is a json object use [some JS package](https://www.google.com/search?hl=en&q=json%20tree%20viewer%20javascript) to display it (in another sub-window?).
For example explore e.g.
 - https://github.com/pgrabovets/json-view 
 - https://www.npmjs.com/package/json-tree-viewer

**Comment by valentinMachado** [comment]
Since this widget is a debug tool, the user has to be a developper meaning its console should be open to see this log. This behavior is documented [here](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Widget/3DTilesDebug/docs/3DTilesDebug.md)
In my opinion introducing a new package dependency + developing this feature is a bit too much.
Maybe we could modify the label button from "Log Tiles Manager" to "Log Tiles Manager in console", what do you think ?

**Comment by DiegoVinasco** [comment]
> Since this widget is a debug tool, the user has to be a developper meaning its console should be open to see this log. This behavior is documented [here](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Widget/3DTilesDebug/docs/3DTilesDebug.md) In my opinion introducing a new package dependency + developing this feature is a bit too much. Maybe we could modify the label button from "Log Tiles Manager" to "Log Tiles Manager in console", what do you think ?

This is perfect in my opinion. To me the widget isn't broken, it's documentation just isn't visible enough (or not being read). Adjusting the button text would make the intended behavior more explicit.

**Comment by valentinMachado** [comment]
Ok that's fine for me. I open a PR https://github.com/VCityTeam/UD-Viz/pull/550 and modify the label from "Log Tiles Manager" to "Log LayerManager in console" since what its logged is the layerManager
