### ISSUE TITLE
What is the relationship between UD-Viz's 3DTiles and iTowns 3DTiles ?

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#342]
## iTowns' vs UD-Viz's 3DTiles modeles

iTowns seems to have a [(model) representation of 3DTiles sub-components](https://github.com/iTowns/itowns/tree/master/src/Core/3DTiles) like :
 * (from top to bottom) [TileSet](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTileset.js), Tile seems to be missing, [BoundingVolumes](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBoundingVolume.js),
 * starting with [Extensions](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTExtensions.js), the [standard BatchTable extension](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTable.js) and the [BatchTable hierarchy extesion](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTBatchTableHierarchyExtension.js)

On the other hand [UD-Viz's 3DTiles model](https://github.com/VCityTeam/UD-Viz/tree/master/src/Components/3DTiles/Model) defines the 3DTiles [Tile class](https://github.com/VCityTeam/UD-Viz/blob/master/src/Components/3DTiles/Model/Tile.js) but apparently nothing about TileSet, BoundingVolume and extensions. Notice that UD-Viz's Tile does not import iTowns's C3DTiles.

Within UD-Viz the **connection** between UD-Viz's (3d)Tile and iTowns' C3DTile is done at the application level e.g. within the [AllWidget.js application template](https://github.com/VCityTeam/UD-Viz/blob/master/src/Templates/AllWidget/AllWidget.js#L443) that 
* [registers the 3DTiles temporal extension](https://github.com/VCityTeam/UD-Viz/blob/master/src/Templates/AllWidget/AllWidget.js#L447)
* [plugs an UD-Viz'sTilesManager within iTown's layerManager](https://github.com/VCityTeam/UD-Viz/blob/master/src/Templates/AllWidget/AllWidget.js#L489)

##  Tile vs CityObject (UD-Viz internal)
[UD-Viz's 3DTile ](https://github.com/VCityTeam/UD-Viz/blob/master/src/Components/3DTiles/Model/Tile.js) depends/uses the [CityObject](https://github.com/VCityTeam/UD-Viz/blob/master/src/Components/3DTiles/Model/Tile.js#L139) class.  Yet `CityObject` is a CityGML abstract notion (refer e.g. to [chapter 9.9 of CityGML](https://portal.ogc.org/files/?artifact_id=16675)) as opposed to a 3DTile notion.

Then UD-Viz uses `CityObject` for interacting with "any" 3D object of the city (picking, retrieving attributes, refer e.g. [here](https://github.com/VCityTeam/UD-Viz/blob/master/src/Components/3DTiles/Docs/3DTilesInteraction.md#Pick-a-city-object)).

Can 3DTiles model be used without using CityObject (currently the implementation does not allow it but could there be some usages/use casees if the implementation were to be modified) ?

**Comment by valentinMachado** [comment]
CityObject and Tile are now deprecated since this [PR](https://github.com/VCityTeam/UD-Viz/pull/612), an equivalent of CityObject is [C3DTFeature](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTFeature.js) of itowns.
There is not Tile class in itowns but this notion exists as [C3DTileset has a tiles attributes](https://github.com/iTowns/itowns/blob/23c16d2bc188bf200011167db6692686d2782163/src/Core/3DTiles/C3DTileset.js#L38) but my little finger tell me that a refactor is planned..
