### ISSUE TITLE
Potential issue with a GML or a 3DTiles

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#346]
I am trying to visualize Villeurbanne using this syntax:

`````
  "3DTilesLayers": [
    {
      "id": "Villeurbanne",
      "url": "https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/Villeurbanne_2018_TileSet/tileset.json",
      "color": "0xFFFFFF"
    }
  ],
``````

As far as I remember it used to work pretty well but now that I am using 2.36 the rendering of the building are wrong for some of them as shown here:

<img width="1303" alt="Screenshot 2022-04-13 at 14 58 02" src="https://user-images.githubusercontent.com/3928502/163185346-11b65a23-4064-4163-b6ca-8b9ce55aa66d.png">
<img width="1239" alt="Screenshot 2022-04-13 at 14 58 31" src="https://user-images.githubusercontent.com/3928502/163185359-1d46f95b-6388-4078-bab5-160cb412962c.png">

**Comment by mathieuLivebardon** [comment]
It seems to work with the version 2.33.1
![2022-04-13_15h08_57](https://user-images.githubusercontent.com/34244904/163187314-caa126c6-c6d2-439e-8236-c66004fb5741.png)

**Comment by agrignard** [comment]
Here is a screenshot with google chrome (v100.0) where the issue is still here on the left  and safari (v15.3) on the right where it is working.

Is there anyone having the same issue on Google chrome with a Mac? If not can it come from my configuraation (wrong version of chrome or something else?)

<img width="1439" alt="Screenshot 2022-04-22 at 11 55 41" src="https://user-images.githubusercontent.com/3928502/164605944-543937d4-841b-4bee-a3a3-90656c696369.png">

**Comment by mathieuLivebardon** [comment]
I was not able to reproduce. It works on **Windows 10** and **ud-viz v2.37.3** on Google Chrome : **Version 100.0.4896.127**, Firefox : **Version 99.0.1** and Microsoft Edge : **Version 100.0.1185.50**.

**Comment by agrignard** [comment]
Ok maybe something related to Mac OS then, I will try to test it also on other computers too

**Comment by agrignard** [comment]
Closing this issue as it seems very specific to the configuration of the computer running the code
