### ISSUE TITLE
Get the current zoom level from the camera height in the PlanarView

### ISSUE THREAD

**Issue by CorentinGaut** [VCityTeam/UD-Viz#369]
In the globe view, we can use  `view.controls.getZoom()` ([here](http://www.itowns-project.org/itowns/docs/#api/Controls/GlobeControls))but not in the planarView. We need this to create new widgets.

**Comment by valentinMachado** [comment]
I started a discussion with itowns => https://github.com/iTowns/itowns/discussions/2017

**Comment by valentinMachado** [comment]
In what purpose do you need the zoom value @CorentinGaut ? would the distance between the ground and the camera works for you ?
