### ISSUE TITLE
Contribute GUI sidebar/widget integration to iTowns

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#373]
When an application uses many widgets there can be a visual bloating.
We might need to regroup the widgets in a side bar (like on a desktop computer)
and be able to pop up the associated widget as a window (resizable, repositionable) 
on top of 3D view.

[Illustrative demo application](https://spatial-multimedia-demo.vcityliris.data.alpha.grandlyon.com/) using a side bar. 

Currently a first/coarse/limited version of such a feature is offered by the [so called GUI component](https://github.com/VCityTeam/UD-Viz/tree/master/src/Widgets/Components/GUI).
It's main current limitation is that the CSS is highly embedded and should be separated.

**Comment by DiegoVinasco** [comment]
Removing iTowns label since the iTowns library does not typically handle UI/UX components of an application.

This issue looks like it is a sub-issue of #403

**Comment by agrignard** [comment]
Close this issue as it's indeed a duplicate of this one https://github.com/VCityTeam/UD-Viz/pull/403
