### ISSUE TITLE
Add modular GUI components like submenus, and tabs

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#378]
Two new ideas inspired from @ClarisseAubert could be added to the UD-Viz GUI components:
- **Widget sidebar submenus**: when clicking on a widget icon on the left sidebar instead of immediately visualizing a widget, a submenu could be shown instead for selecting specific functionality of more complex widgets.

![submenu example](https://user-images.githubusercontent.com/23373264/177121109-09dd35dc-56ce-4638-8283-749aa3282454.png)

- **Widget window tabs**: Some widgets may benefit from a tabular display where instead of visualizing multiple windows (like in the case of the document explorer), a single window with tabs could be shown.

**Comment by valentinMachado** [comment]
After discussion with @DiegoVinasco it appears that GUI stuff is out of the scope of @ud-viz/browser so I am closing this
