### ISSUE TITLE
3D Feature style handling

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#381]
Currently, it is possible to use Style only for FeatureCollection and Feature. It could extended either to handle any geometryLayer, or create a FeatureCollection from 3DTiles (as each object of a 3DTiles can be treated as a feature).

**Comment by valentinMachado** [comment]
Style API of ud-viz has been removed within that [PR](https://github.com/VCityTeam/UD-Viz/pull/612)
itowns includes now a style API working with [C3DTFeature](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTFeature.js) doing what it was possible to do with the old ud-viz api.

Iam not sure to understand the need here, in what way the three.js api is not sufficient for your need ?

**Comment by clementcolin** [comment]
C3DTFeature should be fine, closing
