### ISSUE TITLE
GUI window bug (in temporal widget demo)

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#387]
Moving GUI window in [Temporal widget demo](https://ud-viz.vcityliris.data.alpha.grandlyon.com/examples/TemporalWidget/example.html) is buggy.

When moving the widget, it jumps to the right and refuses to follow the mouse cursor exactly. It also seems to hit a 'barrier' when moving to the left of the screen.

This might also effect other widgets

![chrome-capture-2022-6-15](https://user-images.githubusercontent.com/23373264/179188522-35eb2d09-c86f-4600-86f0-e1b1a660ad0a.gif)

**Comment by valentinMachado** [comment]
Widgets are no longer using Window, so Iam closing this
