### ISSUE TITLE
Update logos for example and demo

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#395]
Obligatoire : 
 - [x] Lidex doit devenir Université de Lyon 

Les autres démos / exemples doivent être personnaliser par projet

**Comment by CorentinGaut** [comment]
Done and each demo/example logos can be personalize in the congig file [here](https://github.com/VCityTeam/UD-Viz/blob/master/examples/assets/config/all_widget_config.json#L5)
