### ISSUE TITLE
Center the view of temporal widget demo on the borough center 

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#399]
## The difficulty
When starting the [temporal widget demo](https://ud-viz.vcityliris.data.alpha.grandlyon.com/examples/TemporalWidget/example.html) the display is not centered on the loaded borough 3DTiles tileset. Because the displayed buildings are too "far away" one cannot distinguish any visual change when the slider is activated (and the demo appears to be failing/meaningless).
Thus a user might believe that all the data was not loaded because of some server/network lag and tends to wait uselessly...

Additionally consider opening the temporal slider window on starting the demo as a visual clue of what this demo might be about.

## Possible solution
Center the initial view on the loaded borough.

**Comment by CorentinGaut** [comment]
[Pull Request 463](https://github.com/VCityTeam/UD-Viz/pull/463)
