### ISSUE TITLE
New version of UDVIZ and dynamic layer not working

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#428]
We are working with @valentinMachado and @mathieuLivebardon to update the ReAgent (Gratte Ciel) demo to make it compatible with the last version of UD_VIZ (2.38)

However after spending time with @valentinMachado we didn't manage to make it work (the install and the build are ok) but not the run time where the bounding box is not displayed as it is suppose to and the dynamic layer either

This is what I have in the old working version (ud_viz 2.37). Boudning box + json layer
<img width="1341" alt="Screenshot 2022-09-19 at 16 15 25" src="https://user-images.githubusercontent.com/3928502/191038728-d32dfa77-3822-4855-b5de-39b5856c0052.png">

and this is what I have with the ud_viz 2.38 (the 3D tile is now displayed by default) but we don't see (actually I see it very quickly the blue bounding box and the json layer)
<img width="1317" alt="Screenshot 2022-09-19 at 16 10 48" src="https://user-images.githubusercontent.com/3928502/191038144-72759fc4-0584-40b5-b345-6b3d66c75b65.png">

The main difference is the usage of ```app.view3D.getItownsView()``` instead of ```app.view```

As agreed with @valentinMachado the current master branch  of reagent is working well with UD_VIZ and can be found here https://github.com/VCityTeam/UD_ReAgent_ABM/tree/master

 and the dev branch is this one https://github.com/VCityTeam/UD_ReAgent_ABM/tree/dev_ud_viz_2_38

**Comment by valentinMachado** [comment]
I found out what was wrong in the config "colorTextureElevationMinZ" + "colorTextureElevationMaxZ" needs to be specify now.
I have created an issue https://github.com/VCityTeam/UD-Viz/issues/429 to warning the user when it's not specify

**Comment by agrignard** [comment]
Awesome! Thank you @valentinMachado for the help.

I merge the branch for now and close this  issue.
