### ISSUE TITLE
Slideshow initial Z value

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Viz#441]
Right now the Z value of the Slideshow is hard coded to 250

https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/SlideShow/SlideShow.js

One first solution can be to reset the Z value of the slideshow sing this
```slideShow.setCoordinatesInputs(newCameraPosition.x,newCameraPosition.y,10);```

**Comment by valentinMachado** [comment]
Need to compute the more elevated point in the elevation_layer => ask itowns if it's possible

**Comment by agrignard** [comment]
This is workling in ReAgent (see this commit https://github.com/VCityTeam/UD_ReAgent_ABM/pull/27/commits/c75b3d857a8f76456cb20b966c567d09055f1958)
but need to be reinjhected in UD_VIZ at some point

**Comment by agrignard** [comment]
@valentinMachado do you know if this has been fixed directly in UD_Viz? If yes this issue can be closed

**Comment by valentinMachado** [comment]
The code have not been done in UD-Viz, but in the UD_Reagent bootstrap.js. Camera position is computed to fit the extent on the max dimension. It could be an UD-Viz features in the THREEUtil file, we should let it open the time to migrate this code.
