### ISSUE TITLE
Game refacto

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#449]
Today we have to mutualize game code such one produced/are going to be produced in this repositories/issues:
- [UD-Imuv](https://github.com/VCityTeam/UD-Imuv)
- [Galeri3](https://github.com/VCityTeam/GALERI3)
- [Deambulation Bron](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron)
- [MSH](https://github.com/VCityTeam/UD-Imuv/issues/311)
- [ENTPE](https://github.com/VCityTeam/UD-Imuv/issues/312)

The aim is to define where belong the code of:
- Game Engine + GameView + AssetsManager + LocalGame Template (actually in ud-viz)
- Editor (actually in UD-Imuv)
- Distant Game client (actually in UD-Imuv)
- Game server (actually in UD-Imuv)
- LocalScripts + WorldScripts (actually splited in differents repositories)

Everything should be package in ud-viz or we should create new npm packages or both ?

**Comment by valentinMachado** [comment]
AssetsManager need to load custom localscript/worldscript and to have native ones (such as avatar_controller, map)

**Comment by mathieuLivebardon** [comment]
![20221024_161553.jpg](https://user-images.githubusercontent.com/34244904/197548014-efea29aa-4d0f-442b-b2a7-8f724249041c.jpg)

**Comment by mathieuLivebardon** [comment]
> Note that with this solution UD-Game example are going to be remove...
The examples using the game engine for the moment in _ud-viz_ could be found in a new mosaic in _ud-viz-game_.

**Comment by mathieuLivebardon** [comment]
![20221024_161553.jpg](https://user-images.githubusercontent.com/34244904/197548014-efea29aa-4d0f-442b-b2a7-8f724249041c.jpg)

**Comment by valentinMachado** [comment]
Creation d'un ud-game-template pour la solution pourrait etre envisagé comme c'est le cas pour ud-viz-template

**Comment by valentinMachado** [comment]
https://github.com/VCityTeam/UD-Viz/issues/245 may be related

**Comment by mathieuLivebardon** [comment]
![20221027_172852.jpg](https://user-images.githubusercontent.com/34244904/198540771-0974d804-a781-49e9-ad8b-5239885a4c8c.jpg)
![20221027_173104.jpg](https://user-images.githubusercontent.com/34244904/198540796-3406941e-b9f5-45d8-b582-c8eef476e0b3.jpg)
![20221027_173209.jpg](https://user-images.githubusercontent.com/34244904/198540817-39ebf652-e754-46f8-8d32-7e47079bcaae.jpg)

**Comment by valentinMachado** [comment]
Actually what has been identify is the need to have three npm projects => a node + browser compatible (ud-viz-core?) + a browser compatible importing ud-viz-core (ud-viz-client?) + a node compatible importing as well ud-viz-core (ud-viz-server?). All we need to discuss is if we prefer a multi repo or a mono repo approach => [more details here](https://kinsta.com/blog/monorepo-vs-multi-repo/). In my opinion I rather the mono repo approach in this case for the following reasons:

- It's Lowers Barriers of Entry for new developpers (all documentation + all sources in the same place), which is good for an open source project + to make easier the internshipper life
- Less repo (actually [UD-SimpleServer](https://github.com/VCityTeam/UD-SimpleServer) should be also deprecated) in regard to the number of repo in VCity, it should be great
- It shows that dependencies (npm one + mechanical one) between these npm project is strong (ud-viz and ud-game work all together !) and simplify big code refacto.
- That's not more complicated to maintain and in a way could be consider more easier, the only constraint is to synchronized versionning between the three npm projects and the repo versioning. One problem is if a npm project is being developed more quickly than the others, it force the others to change their version even there were no changes, which should not be a problem since that's the case today in ud-viz since ud-viz-core is mixed in ud-viz-client (forming the current ud-viz).

The multi repo works as well, and it fine for me, the main advantage is to have a version for each repo/npm project.

**Comment by mathieuLivebardon** [comment]
Source Archi draw on whiteboard w/EBO MLI

![20221107_160134.jpg](https://user-images.githubusercontent.com/34244904/200351851-74a86631-b8c0-437a-a845-da0004786178.jpg)

**Comment by mathieuLivebardon** [comment]
Topic Meeting which validate the solution:
https://github.com/VCityTeam/VCity/blob/master/Topic_Meetings/2022/2022_12_02_Proposition_Refacto_UDVIZ_Game_Part_2.md
