### ISSUE TITLE
City object filters not working

### ISSUE THREAD

**Issue by CorentinGaut** [VCityTeam/UD-Viz#461]
#### Steps to reproduce:
* Open the `AllWidgets` example
* Move in the 3D scene in order to see the Perrache train station
* Open the `City Objects` window from the left side menu bar
* Click on the `Select` button under the `Filter` category
* Select `Attributes` in the first drop-down menu
* Enter a `Tile ID` (e.g. 1 for the Perrache station) and a `Batch ID` (e.g. 5889 for the Perrache station)
* Click on `Set Filter`

#### Expected behavior:
The selected city object (e.g. the Perrache station) should be colored in orange.

#### Short term:

Try to locate where this bug comes from (most likely from a recent pull request); e.g. by using [git-bisect](https://git-scm.com/docs/git-bisect) and fix it.

Note: Selecting city objects from the scene by clicking them with the `City Object` window opened works (the selected city object is colored in blue and its attributes are displayed in the city object window). Finding the differences between this functionalities and the broken ones may help fixing these bugs.

#### Long term:

Implement a test suite in UD-Viz, otherwise features may be lost over time... For this purpose, get inspiration from itowns that uses [mocha](https://mochajs.org/) as a test-framework and [puppeteer](https://github.com/puppeteer/puppeteer) to simulate a web browser.

**Comment by valentinMachado** [comment]
Related to how works StyleManager + TilesManager + CityObject + CityObjectLayer which are classes not existing (yet ?) in itowns. Before continuing to support them we have to define if these classes are going to belong to itowns or not. If not imo this would mean that it's possible to do the same thing without these class in a pur itowns style making our itowns widget compatible to be contributed to their project. Or if yes these classes will belong to itowns making in anycase our widget compatible to be transfer in itowns project. This subject becomes more and more important and needs to be discussed for each class. I will create discussion about it.

**Comment by valentinMachado** [comment]
CityObject is now deprecated since this [PR](https://github.com/VCityTeam/UD-Viz/pull/612), an equivalent is [C3DTFeature](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTFeature.js) of itowns.

A [new widget](https://github.com/iTowns/itowns/blob/master/src/Utils/gui/C3DTilesStyle.js) to customize C3DTFeature has been implemented in itowns/widget [example here](https://github.com/iTowns/itowns/blob/master/examples/widgets_3dtiles_style.html)
