### ISSUE TITLE
ComputeNearFar camera height

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#469]
Today the camera near and far are computed dynamically according the extent for xy plane and z hardcoded value (400).

Problem: when the camera is looking z=-1 above this harcoded value the near crop the scene 3D

Solution: make this hardcoded value expose in config or find a smart way to compute this value

**Comment by LorenzoMarnat** [comment]
Near/far computation in iTowns [PlanarView](https://github.com/iTowns/itowns/blob/023d5faf2112d36916affdb722ce98236038d2c5/src/Core/Prefab/PlanarView.js#L47)

**Comment by valentinMachado** [comment]
> Near/far computation in iTowns [PlanarView](https://github.com/iTowns/itowns/blob/023d5faf2112d36916affdb722ce98236038d2c5/src/Core/Prefab/PlanarView.js#L47)

Yeah the problem here is this is kind of arbitrary and not dynamic, this is why we are computed near far in ud-viz with
[computeNearFar](https://github.com/VCityTeam/UD-Viz/blob/02809e214dc3d64bedf9616bd69f0ab389321fe0/packages/browser/src/Component/THREEUtil.js#L109) recorded in the main loop of itowns [here](https://github.com/VCityTeam/UD-Viz/blob/02809e214dc3d64bedf9616bd69f0ab389321fe0/packages/browser/src/Component/Frame3D/Frame3DPlanar.js#L82)

This is working well except in the case I was describing above, the good solution which is to compute dynamically min and max z of the scene. To achieve that we could recording in the TILE_LOAD event a listener which update the min and max Z of 3DTiles based on the bounding box. Then to compute dynamically min and max Z of the scene we could make:

```
const minZScene =  Math.min(minZ3DTiles, colorTextureMinElevation)
const maxZScene =  Math.max(maxZ3DTiles, colorTextureMaxElevation)
```

Since sometimes this is the elevation layer which bounding the scene and sometimes the 3DTiles. A problem remain which is object3D in the scene which are not 3DTiles (like gameobject) are not going to be consider, but these objects are going maybe to be transform in 3DTiles so for now I think this fix should be good enough
