### ISSUE TITLE
Reduce Widget

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Viz#473]
Add button or/and input to reduce a window of widget (to keep the widget in the background).

![Minimize-Maximize-Close-Window-512-2781796926](https://user-images.githubusercontent.com/34244904/205067260-4d3fadaa-c516-4200-bee7-4f49ae57c7da.png)

> It could be useful for the https://github.com/VCityTeam/UD_ReAgent_ABM demo.

**Comment by agrignard** [comment]
We now have this feature ready and working in the new slideshow widget (pressing A and S)
