### ISSUE TITLE
gitignore ./docs/html

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#477]
Should we gitignore ./docs/html ?

In my opinion YES since this is generated files and we could build them at the deploy time like ./dist bundle folder.
It will also avoid useless HUGE gitdiff at each release.

**Comment by johnsamuelwrites** [comment]
We are using GitHub pages. Please refer to the site: https://vcityteam.github.io/UD-Viz/html/index.html

I feel that it's important to have this folder docs/html. There is another way where you can create a branch gh-pages which will contain all the necessary static pages. 

Reference: https://pages.github.com/

**Comment by valentinMachado** [comment]
Or create a branch gh generated

**Comment by EricBoix** [comment]
The ` ./docs/html` content is only updated when the documentation is regenerated which only happens when making a new release.

**Comment by clementcolin** [comment]
AI : 
- Move the doc to a 'doc'
- Change source of the github page to this 'doc' branch
- On the master branch, add the doc to a .gitignore
- Create Github Action to, on release : 
  - Merge the master branch to the doc branch
  - Regenerate the doc

**Comment by JPugetGil** [comment]
Ref : https://github.com/marketplace/actions/deploy-to-github-pages
