### ISSUE TITLE
Publish three packages npm

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#489]
Update process of release
Create command associated

These issues should be done before publishing:
https://github.com/VCityTeam/UD-Viz/issues/488
https://github.com/VCityTeam/UD-Viz/issues/482
https://github.com/VCityTeam/UD-Viz/issues/481

**Comment by mathieuLivebardon** [comment]
https://www.npmjs.com/package/@ud-viz/shared

https://www.npmjs.com/package/@ud-viz/node

https://www.npmjs.com/package/@ud-viz/browser
