### ISSUE TITLE
Create a generic function to add logos UDL + LIRIS

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#496]
AllWidget template is already doing it the idea is to make a generic method so all templates could easily add logos

**Comment by CorentinGaut** [comment]
WIP in the CSSCleanUp branch

**Comment by valentinMachado** [comment]
Iam not sure this is still relevant, actually all the code to do that is more or less css. Since we want to move css from src this method will be an empty shell linking css class to dom element.

WDYT ?
