### ISSUE TITLE
Widget Documents : errors inside the console

### ISSUE THREAD

**Issue by JPugetGil** [VCityTeam/UD-Viz#504]
When I'm double clicking on the icon widget, we have an error inside the console.
The widget is trying to insert an image inside an element that doesn't exist anymore.

**Comment by valentinMachado** [comment]
I've tried to reproduce this bug on this [branch](https://github.com/VCityTeam/UD-Viz/tree/584-clean-itowns-folder) (which will be merged to master soon) but I did not succeed. So I am assuming this bug has been resolved, could you please confirm it @JPugetGil

**Comment by JPugetGil** [comment]
It's now working properly, thanks !
