### ISSUE TITLE
Detail usage of label

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#521]
Today there are many labels but there is no global logic.
Can be nice to determine one and to document it in Contributing.md

**Comment by valentinMachado** [comment]
As explained here https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/Devel/Contributing.md#prior-to-pr-submission
when a PR is created means that the code is mature (to avoid to push on a branch related to PR that will trigger CI everytime wasting travis token).
We should remove label "DO NOT MERGE YET", if a PR is not ready this means that it's reviewers requesting changes.

**Comment by mathieuLivebardon** [comment]
Maybe we can use the "Convert to Draft" function for Pull Request. It seems to me a solution to get rid of the "DO NOT MERGE YET".
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by valentinMachado** [comment]
I Agree, I removed `Pr ready` and `DO NOT MERGE YET` we should use draft github feature. 
> Note that pushing on a draft PR will trigger travis CI anyway
