### ISSUE TITLE
address search pin geomertry is bugged

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#528]
When using the address search in the AllWidget example in v3.0.0 I see this :

![image](https://user-images.githubusercontent.com/23373264/218997765-0ff95178-e5a7-4c6e-a4d7-5589f8570a7b.png)

Does anyone else have this experience?

**Comment by DiegoVinasco** [comment]
Also the geocoding example

**Comment by valentinMachado** [comment]
> When using the address search in the AllWidget example in v3.0.0 I see this :
> 
> ![image](https://user-images.githubusercontent.com/23373264/218997765-0ff95178-e5a7-4c6e-a4d7-5589f8570a7b.png)
> 
> Does anyone else have this experience?

Yeah I also saw that this was the case before the v3.0.0
