### ISSUE TITLE
Write a CONTRIBUTORS.md 

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Viz#556]
List the names of people with links to their Github pages and what organization they are from.

**Comment by EricBoix** [comment]
This issue is tightly related to #555 .
In order to create the file we should cross the information of 

[the project members](https://projet.liris.cnrs.fr/vcity/general/team/)

and

```bash
git log | grep Author | sed 's/^Author: //' | \
   sed 's/jailln/Jaillot Vincent/' | \
    sed 's/John Samuel <johnsamuelwrites@gmail.com>/John SAMUEL/'| \
    sed 's/John SAMUEL <john.samuel@liris.cnrs.fr>/John SAMUEL/' | \
    sed 's/John Samuel <johnsamuelwrites@users.noreply.github.com>/John SAMUEL/' | \
    sed 's/frogsapo <eric.boix@gmail.com>/Eric BOIX/' |  \
    sed 's/Mathieu <>/Mathieu LIVEBARDON/' | \
    sed 's/Mathieu Livebardon <34244904+mathieuLivebardon@users.noreply.github.com>/Mathieu LIVEBARDON/' | \
    sed 's/Mathieu <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
    sed 's/Mathieu Livebardon <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
    sed s'/mathieuLivebardon <>/Mathieu LIVEBARDON/' | \
    sed s'/mathieuLivebardon <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
    sort -u
```

**Comment by mathieuLivebardon** [comment]
> This issue is tightly related to #555 . In order to create the file we should cross the information of
> 
> [the project members](https://projet.liris.cnrs.fr/vcity/general/team/)
> 
> and
> 
> ```shell
> git log | grep Author | sed 's/^Author: //' | \
>    sed 's/jailln/Jaillot Vincent/' | \
>     sed 's/John Samuel <johnsamuelwrites@gmail.com>/John SAMUEL/'| \
>     sed 's/John SAMUEL <john.samuel@liris.cnrs.fr>/John SAMUEL/' | \
>     sed 's/John Samuel <johnsamuelwrites@users.noreply.github.com>/John SAMUEL/' | \
>     sed 's/frogsapo <eric.boix@gmail.com>/Eric BOIX/' |  \
>     sed 's/Mathieu <>/Mathieu LIVEBARDON/' | \
>     sed 's/Mathieu Livebardon <34244904+mathieuLivebardon@users.noreply.github.com>/Mathieu LIVEBARDON/' | \
>     sed 's/Mathieu <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
>     sed 's/Mathieu Livebardon <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
>     sed s'/mathieuLivebardon <>/Mathieu LIVEBARDON/' | \
>     sed s'/mathieuLivebardon <tsunoll96@gmail.com>/Mathieu LIVEBARDON/' | \
>     sort -u
> ```

git log provides an option `--pretty` for formatting the output of the command. 
I suggest using this command instead : `git log --pretty=format:"%aN -- %aE" | sort -uf`

**Comment by EricBoix** [comment]
@mathieuLivebardon 
Because we have to manually resolve aliases and still count commits, I propose [this PR](https://github.com/VCityTeam/UD-Viz/pull/685) that gives up on shell level tricks and pulls python to get the job done.
