### ISSUE TITLE
Clean CityObject

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#594]
This class should be the first thing to discuss, as many of the other issue of #590 and thus #584 are related to it.
Basically it's record an interval in the vertex array of the 3DTile (or a batch id) to attach some semantic to it (props which are stored in the batchtable)

For me it's not relevant but I might miss some use case so do not hesiate to expose your opinion over there.

## References
- Corresponding [iTowns discussion](https://github.com/iTowns/itowns/discussions/2054)

**Comment by EricBoix** [comment]
Hints:
* The only occurrences of instantiation are within Tile.js and are [here](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Itowns/3DTiles/Model/Tile.js#L168) and [there](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Itowns/3DTiles/Model/Tile.js#L198)
* py3dTilers has an equivalent notion of [citym_cityobject](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/citym_cityobject.py)
* IMHO The original notion for the creation of the CityObject class was to try to retrieve some CityGML semantics after the loss of that data source domain information when squeezing things into a 3DTile (that has no notion of CityGML or IFC data model).

**Comment by valentinMachado** [comment]
Hints:

* https://github.com/VCityTeam/UD-Viz/issues/342
* https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/Devel/UD_Viz_Browser/3DTiles/3DTilesInteraction.md#city-object

**Comment by valentinMachado** [comment]
> * py3dTilers has an equivalent notion of [citym_cityobject](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/citym_cityobject.py)


[Here](https://github.com/VCityTeam/UD-Viz/blob/95fead701b727f51aea2d134c79d1c07b709bf8b/docs/static/Devel/UD_Viz_Browser/3DTiles/3DTilesUtils.md#batch-table) it's writed that you can also attached a batch id to a cityobject.database_id (pointing to the one you mentioned I guess/hope) via batchtable. If that's the case, since this data (cityobject.database_id) is optional in batchtable (it could be empty or point to a gml_id) calling a batch id a CityObject in ud-viz is confusing/wrong.

**Comment by valentinMachado** [comment]
> * Style CityObject (or traditionally, Feature) in a 3DTiles tileset.
>   3DObject styling still need further research and experimentation, but it can be made generic and only associated to the 3DTiles concept (i.e free from the CityObject class)

itowns has a [Style class](https://github.com/iTowns/itowns/blob/master/src/Core/Style.js) what we could do is a converter function to a THREE.Material (a first implementation could be the color of the material is the [fill color](https://github.com/iTowns/itowns/blob/b5123f51b8f43e89adc5903c13048338ab9f1e16/src/Core/Style.js#L322)) in the futur it could be a bit more complex (if we handle outline and so on)

From what you said every functionalities seems to be already in itowns (except maybe for some stateless util methods, that should be easy to contribute).

So CityObject class + CityObjectStyle #595 should go home
