### ISSUE TITLE
Examples do not register epsg 3946 correctly

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#625]
Currently, in the examples, we register a new projection system using the name in the config file with the parameter of the epsg 3946.
See [here](https://github.com/VCityTeam/UD-Viz/blob/master/examples/3DTilesWireframe.html#L24)

This line should not depend on the config file as it set a newly available projection system for proj4.

**Comment by valentinMachado** [comment]
What would be a solution ? Propose a PR to [proj4](https://github.com/proj4js/proj4js) so the projection EPSG:3946 would a default projection ? Remove crs fields of the config ?
