### ISSUE TITLE
Clean `SideBarWidget`

### ISSUE THREAD

**Issue by valentinMachado** [VCityTeam/UD-Viz#646]
`SideBarWidget` should as Widget propose an API to customize css (take className as parameter) in order to remove all css of src in the futur. It should also be renamed (this name is confusing since the side bar is not the widget) but Iam not sure about the name..

The word "application" could be part of the name since this is an application in contrary to @ud-viz/browser `Component` but I don't think SideBarApplication is a good name since another application with a side bar (exactly the same one if we decide to factorized the sidebar ui code in `GUI`) could be implemented doing other stuff.

Imo SideBarWidget behavior cant be summarized within its name. It will be the case for all our application..

We could decide to simply name our application `Application1` `Application2` and so on but that's quite boring, I rather doing like [Android version history](https://en.wikipedia.org/wiki/Android_version_history) and naming our application with some lexical word that we have choose.

WDYT ?

EDIT 1: Maybe the name of `SideBarWidget` could be `Visualizer` 

EDIT 2: To introduce the word Application we could remove the Component folder and create a folder Application to put all our Application in it

**Comment by EricBoix** [comment]
In essence SideBarWidget is indeed a very specialized application acting as a showroom for a large set of Ud-Viz features including many widget, drag-&-drop, gaming and the infamous SIDEBAR.
Thus it does not belong into one of the js packages but 
* either in the examples 
* or even outside the repository e.g. in a separate new repository or integrated as a sub-demo of UD-Viz-template.
