### ISSUE TITLE
Architecture: Extensions

### ISSUE THREAD

**Issue by Crejak** [VCityTeam/UD-Viz#66]
Is the folder "Extensions" still needed ? Should we merge it with the "Modules" ?

**Comment by jailln** [comment]
I think we should merge it with the "Modules" folder to simplify UD-Viz organisation.

**Comment by EricBoix** [comment]
The source layout is [now documented](https://github.com/VCityTeam/UD-Viz#sources-directory-layout-organizational-principles) (and less evolutive).
Closing.
