### ISSUE TITLE
Color of 3DTiles Layer Config is useless

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#693]
The color field in the [3DTiles layer config file](https://github.com/VCityTeam/UD-Viz/blob/master/examples/assets/config/layer/3DTiles.json#L5) is useless, as we do not process it anymore when creating a layer using the [createC3DTilesLayer](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/ItownsUtil.js#L18C17-L18C36) method in the ItownsUtils

**Comment by valentinMachado** [comment]
IMO these "add" functions in ItownsUtil should be removed and we should use itowns API instead. In the future if we want to have 3DTiles style config files we should use [Cesium convention](https://github.com/CesiumGS/3d-tiles/tree/main/specification/Styling)   refer to this [itowns discussion](https://github.com/iTowns/itowns/discussions/2085)
