### ISSUE TITLE
Refactor docToValidate to support dynamic fields

### ISSUE THREAD

**Issue by Crejak** [VCityTeam/UD-Viz#79]
# Context

For the moment, the search fields and the displayed properties of a document in validation are hardcoded in the front-end.

# Problem

If the document model change, the developpers would have to change the code of the module to be up-to-date with the new model. It would be more practical to generate these fields according to the config file provided, like in ConsultDoc module.

**Comment by DiegoVinasco** [comment]
Closed during UD-Viz sprint

this concerns multimedia DB
